chore(pre-commit): enable trailing-whitespace check

diff --git a/init.d/ais-forward b/init.d/ais-forward
--- a/init.d/ais-forward
+++ b/init.d/ais-forward
@@ -3,7 +3,7 @@
 ### BEGIN INIT INFO
 # Provides:        ais-forward
 # Required-Start:  $ntp $log-ais
-# Required-Stop:   
+# Required-Stop:
 # Default-Start:   2 3 4 5
 # Default-Stop:    0 1 6
 # Short-Description: Start tide logging daemon
@@ -25,7 +25,7 @@ PIDFILE=$PIDDIR/ais-forward.pid
 LOGDIR=/var/log/datalogging
 LOGFILE=${LOGDIR}/${NAME}.log
 
-test -x $DAEMON || echo "ERROR: can not find forwarding daemon: $DAEMON"  
+test -x $DAEMON || echo "ERROR: can not find forwarding daemon: $DAEMON"
 test -x $DAEMON || exit 5
 
 #if [ -r /etc/default/$NAME ]; then
@@ -51,11 +51,11 @@ case $1 in
 
 		if [ ! -d $PIDDIR ]; then
 		    mkdir -p $PIDDIR
-		    chown $RUNASUSER $PIDDIR 
+		    chown $RUNASUSER $PIDDIR
 		fi
 		if [ ! -d $LOGDIR ]; then
 		    mkdir -p $LOGDIR
-		    chown $RUNASUSER $LOGDIR 
+		    chown $RUNASUSER $LOGDIR
 		fi
 
 		# FIX: make this read through a list of loggers to run with parameters
diff --git a/init.d/logais b/init.d/logais
--- a/init.d/logais
+++ b/init.d/logais
@@ -3,7 +3,7 @@
 ### BEGIN INIT INFO
 # Provides:        logais
 # Required-Start:  $ntp
-# Required-Stop:   
+# Required-Stop:
 # Default-Start:   2 3 4 5
 # Default-Stop:    0 1 6
 # Short-Description: Start ais logging daemon
@@ -22,7 +22,7 @@ PIDDIR=/var/run/data
 PIDFILE=$PIDDIR/logais.pid
 
 
-test -x $DAEMON || echo "ERROR: can not find logger daemon: $DAEMON"  
+test -x $DAEMON || echo "ERROR: can not find logger daemon: $DAEMON"
 test -x $DAEMON || exit 5
 
 UGID=$(getent passwd $RUNASUSER | cut -f 3,4 -d:) || true
@@ -40,7 +40,7 @@ case $1 in
 
 		if [ ! -d $PIDDIR ]; then
 		    mkdir -p $PIDDIR
-		    chown $RUNASUSER $PIDDIR 
+		    chown $RUNASUSER $PIDDIR
 		fi
 		# FIX: make this read through a list of loggers to run with parameters
 		# How to control all of the loggers in batch or one at a time?
